routes/web.php
<?php
require __DIR__ . '/backend/web.php';
require __DIR__ . '/frontend/web.php';

app/Http/Controllers/Backend/PageGroupController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\PageGroupRequest;
use App\Models\CategoryGroup;
use App\Models\PageGroup;
use App\Models\PageCategory;
use Illuminate\Http\Request;

class PageGroupController extends Controller
{
    public function index(Request $request)
    {
        $categoryId = intval($request->get('category_id'));

        $select = PageGroup::with('categories')->withCount('categories', 'pages');

        if($categoryId) {
            $ids = CategoryGroup::wherePageCategoryId($categoryId)->pluck('page_group_id');
            $select->whereIn('id', $ids);
        }

        $pageGroupsCount = $select->count();
        $pageGroups = $select->latest()->get();

        $categories = PageCategory::with('groups')->latest()->get();

        return view('backend.modules.page.group.browse', compact('pageGroups', 'pageGroupsCount', 'categories', 'categoryId'));
    }

    private function createEdit(PageGroup $pageGroup, $actionMode)
    {
        $categories = PageCategory::all();
        $selectedCategoryIds = $pageGroup->exists ? $pageGroup->categories()->pluck('page_category_id')->toArray() : [];

        return view('backend.modules.page.group.read', compact('pageGroup', 'actionMode', 'categories', 'selectedCategoryIds'));
    }

    public function create()
    {
        return $this->createEdit(new PageGroup(), 'Create');
    }

    public function edit(PageGroup $pageGroup)
    {
        return $this->createEdit($pageGroup, 'Edit');
    }

    public function update(PageGroupRequest $request, PageGroup $pageGroup)
    {
        return $this->save($request, $pageGroup);
    }

    public function store(PageGroupRequest $request)
    {
        return $this->save($request, new PageGroup());
    }

    public function destroy(PageGroup $pageGroup)
    {
        if ($pageGroup->exists) {
            $pageGroup->delete();
        }

        return ['status' => 'success', 'message' => __('alerts.success.deleted')];
    }

    private function save(PageGroupRequest $request, PageGroup $pageGroup)
    {
        $action = $pageGroup->exists ? 'updated' : 'created';

        $attributes = $request->all();

        $pageGroup->fill($attributes)->save();

        if(isset($attributes['categories'])) {
            $pageGroup->categories()->sync($attributes['categories']);
        }
        else {
            $pageGroup->categories()->detach();
        }

        return redirect(route('admin.page-groups.edit', $pageGroup->id))->with('message-success', __("alerts.success.$action"));
    }
}

resources/views/backend/modules/page/group/browse.blade.php
@php
    /**
     * @var $group \App\Models\PageGroup
     */
@endphp


@extends('backend.layouts.master')

@section('title', 'Page Groups')

@section('page-title')
    <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Page Groups</span> - list of page groups</h4>
@endsection

@section('heading-elements')
    @include('backend.components.create-new', ['name' => 'Page Group', 'route' => 'admin.page-groups.create', 'icon' => 'icon-file-plus'])
@endsection

@section('breadcrumbs')
    @include('backend.components.breadcrumbs', ['current' => 'Page Groups'])
@endsection

@section('content')
    <div class="panel panel-flat">

        @include('backend.components.panel-heading', ['title' => 'Page Groups data table', 'count' => $pageGroupsCount])

        <div class="dataTables_wrapper">
            <div class="datatable-header">
                <form action="{{ route('admin.page-groups.index') }}" method="GET">
                    <div class="form-group col-sm-4">
                        <label>Category</label>
                        <select class="form-control" name="category_id" onchange="$(this).closest('form').submit();">
                            <option value="0">All</option>
                            @foreach($categories as $category)
                                <option {{ $categoryId == $category->id ? ' selected' : '' }} value="{{ $category->id }}">[{{ $category->groups->count() }}] {{ $category->name }}</option>
                            @endforeach
                        </select>
                    </div>
                </form>
            </div>

            <table class="table datatable-html table-hover">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Categories</th>
                    <th>Pages</th>
                    <th>Created</th>
                    <th class="text-center">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($pageGroups as $group)
                    <tr>
                        <td>{{ $group->id }}</td>
                        <td>
                            <a href="{{ route('admin.page-groups.edit', ['pageGroup' => $group->id]) }}">{{ $group->name }}</a>
                        </td>
                        <td><a href="{{ route('admin.page-categories.index', ['group_id' => $group->id]) }}" class="label label-{{ $group->categories_count > 0 ? 'success' : 'default' }}">{{ $group->categories_count }}</a></td>
                        <td><span class="label label-{{ $group->pages_count > 0 ? 'success' : 'default' }}">{{ $group->pages_count }}</span></td>
                        <td>{{ $group->created_at }}</td>
                        <td class="text-center">
                            <ul class="icons-list">
                                <li>
                                    <a data-original-title="Edit" data-popup="tooltip" href="{{ route('admin.page-groups.edit', ['id' => $group->id]) }}"><i class="icon-pencil5 text-blue"></i></a>
                                </li>
                                <li>
                                    <a data-original-title="Delete" data-popup="tooltip" data-href="{{ route('admin.page-groups.destroy', ['id' => $group->id]) }}" data-method="delete" class="jquery-postback"><i class="icon-trash text-danger"></i></a>
                                </li>
                            </ul>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>

@endsection

resources/views/backend/modules/page/group/read.blade.php
@php
    /**
     * @var $pageGroup \App\Models\PageGroup
     */
@endphp

@extends('backend.layouts.master')

@section('title', 'Page')

@section('page-title')
    <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Page Group</span> - {{ $actionMode }}</h4>
@endsection

@section('heading-elements')
    @include('backend.components.create-new', ['name' => 'Page Group', 'route' => 'admin.page-groups.create', 'icon' => 'icon-file-plus'])
@endsection

@section('breadcrumbs')
    @include('backend.components.breadcrumbs', ['current' => 'Page Group', 'elements' => [
        'admin.page-groups.index' => 'Page Groups'
    ]])
@endsection

@section('content')

    <div class="col-lg-12">
        <div class="panel panel-flat">
            @include('backend.components.panel-heading', ['title' => 'Edit Page Group data'])

            <div class="panel-body">

                <form action="{{ $pageGroup->exists ? route('admin.page-groups.update', ['pageGroup' => $pageGroup->id]) : route('admin.page-groups.store') }}" method="post" class="form-horizontal">

                    @csrf

                    @if($pageGroup->exists) {{ method_field('PUT') }} @endif

                    <input type="hidden" name="id" value="{{ $pageGroup->id }}"/>

                    <fieldset class="content-group">

                        @if($pageGroup->exists)
                            @include('backend.components.form.timestamps', ['model' => $pageGroup])
                        @endif

                        <div class="form-group">
                            <label class="control-label col-lg-2">Categories</label>
                            <div class="col-lg-10">
                                <select name="categories[]" multiple="multiple" class="select">
                                    @foreach($categories as $category)
                                        <option {{ in_array($category->id, $selectedCategoryIds) ? 'selected=selected' : '' }} value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        @include('backend.components.form.text-field', [
                            'name' => 'name',
                            'is_required' => true,
                            'errors' => $errors,
                            'model' => $pageGroup,
                        ])

                        @include('backend.components.form.text-field', [
                            'name' => 'slug',
                            'is_required' => true,
                            'errors' => $errors,
                            'model' => $pageGroup,
                        ])

                        <button class="btn btn-primary" type="submit">{{ $actionMode }} Page Group</button>

                    </fieldset>
                </form>

            </div>
        </div>
    </div>

@endsection